### ISSUE TITLE
3DPW parsed data link broken

### ISSUE THREAD

**Issue by ichbill** [hongsukchoi/3DCrowdNet_RELEASE#17]
Hi, thanks for your excellent work! But when I tried to reproduce the results, the 3DPW parsed data link listed in https://github.com/hongsukchoi/3DCrowdNet_RELEASE/blob/3d84d17797e353aaf49acfd8087637eca2877292/assets/directory.md is broken. It requires access, but I couldn't send a request.

Could you fix this problem?

**Comment by hongsukchoi** [comment]
Yeah one of my gmail account is suddenly erased… Working on restoring it

**Comment by hongsukchoi** [comment]
Yeah one of my gmail account is suddenly erased… Working on restoring it

**Comment by hongsukchoi** [comment]
@ichbill Hello, I updated. It should work now. Click the new link

**Comment by ichbill** [comment]
The new link works. Thank you!
