### ISSUE TITLE
How to preprocess the 3dpw dataset?

### ISSUE THREAD

**Issue by xljh0520** [hongsukchoi/3DCrowdNet_RELEASE#19]
Sorry to bother you again. :(
I have a question about the SMPL parameters in the 3dpw dataset you offered.
I noticed the pose parameter (72,) and trans parameters (3,) differ from the official 3dpw dataset. So, I guess there are some preprocess in making the annotation. Could you tell me how you preprocess it?
Thanks in advance.~

**Comment by hongsukchoi** [comment]
Hi! Please check here:
https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/master/data/3dpw2coco.py

Best regards,
Hongsuk Choi
https://hongsukchoi.github.io/


2022년 9월 29일 (목) 오전 1:34, Jiahao Li ***@***.***>님이 작성:
