### ISSUE TITLE
About MSCOCO train annotation file

### ISSUE THREAD

**Issue by uyoung-jeong** [hongsukchoi/3DCrowdNet_RELEASE#3]
I am trying to run train script, but there is an issue about annotation file.
Current code tries to read 'MSCOCO_train_SMPL_NeuralAnnot.json' insead of 'coco_smplifyx_train.json': https://github.com/hongsukchoi/3DCrowdNet_RELEASE/blob/c4d32c0dbb2675b022f9bc2848a39242d1142244/data/MSCOCO/MSCOCO.py#L66

Is it correct to comment the 66th line and uncomment the 67th line? Or should we use 'MSCOCO_train_SMPL_NeuralAnnot.json'?

**Comment by hongsukchoi** [comment]
Hi, I updated the `directory.md` lately.

Please use NeuralAnnot :) You can download it from here: https://github.com/mks0601/NeuralAnnot_RELEASE

**Comment by uyoung-jeong** [comment]
Ah thanks!
