### ISSUE TITLE
minor issue: readme correction

### ISSUE THREAD

**Issue by YrralH** [hongsukchoi/3DCrowdNet_RELEASE#35]
In <https://github.com/hongsukchoi/3DCrowdNet_RELEASE/blob/main/assets/directory.md#pytorch-smpl-layer-and-vposer>
The description is 

> Download basicModel_f_lbs_10_207_0_v1.0.0.pkl, basicModel_m_lbs_10_207_0_v1.0.0.pkl, and basicModel_neutral_lbs_10_207_0_v1.0.0.pkl from [here](https://smpl.is.tue.mpg.de/download.php) (female & male) and [here](http://smplify.is.tue.mpg.de/) (neutral) to ${ROOT}/smplpytorch/smplpytorch/native/models.

It seems that it should be ```${ROOT}/common/utils/smplpytorch/smplpytorch/native/models.``` rather than ```${ROOT}/smplpytorch/smplpytorch/native/models```.

**Comment by hongsukchoi** [comment]
@YrralH  Thank you!
