### ISSUE TITLE
About MuPoTs evaluation

### ISSUE THREAD

**Issue by uyoung-jeong** [hongsukchoi/3DCrowdNet_RELEASE#5]
Your paper reports evaluation resluts of MuPoTS-3D, but there are several procedures I could not fully understand.
1) 
Your data loading script(data/MuPoTs/MuPoTs.py) reads preprocessed 2d pose estimator results based on annotation id. Does this mean that you used ground-truth bounding boxes for retrieving 2d predictions?
2) 
At https://github.com/hongsukchoi/3DCrowdNet_RELEASE/blob/c4d32c0dbb2675b022f9bc2848a39242d1142244/data/MuPoTs/MuPoTs.py#L80, your code specifies to use joint regressor weights of mpi-inf-3dhp dataset.
Is this file made by yourself?
As far as I know, previous works(including https://github.com/JiangWenPL/multiperson) used J_regressor_extra.npy for evaluation on mpi-inf-3dhp and MuPoTS.

**Comment by hongsukchoi** [comment]
1) No. 
2) I got the file from my colleague. You can see the difference by visualizing keypoints in images. I am not sure right now but I think I used it because it has more accurate hip joints comparing to the GT.

**Comment by uyoung-jeong** [comment]
Thanks for the reply. :)

**Comment by uyoung-jeong** [comment]
> > Your paper reports evaluation resluts of MuPoTS-3D, but there are several procedures I could not fully understand. 1) Your data loading script(data/MuPoTs/MuPoTs.py) reads preprocessed 2d pose estimator results based on annotation id. Does this mean that you used ground-truth bounding boxes for retrieving 2d predictions? 2) At
> > https://github.com/hongsukchoi/3DCrowdNet_RELEASE/blob/c4d32c0dbb2675b022f9bc2848a39242d1142244/data/MuPoTs/MuPoTs.py#L80
> > 
> > , your code specifies to use joint regressor weights of mpi-inf-3dhp dataset.
> > Is this file made by yourself?
> > As far as I know, previous works(including https://github.com/JiangWenPL/multiperson) used J_regressor_extra.npy for evaluation on mpi-inf-3dhp and MuPoTS.
> 
> Hi, did you reproduce the result on MuPoTS? If so, could you share your preprocessed annotation file? Thanks in advance!

No, I have no idea how to reproduce the result. It's better to ask the author to release related information.
