### ISSUE TITLE
how to convert the result to bvh file?

### ISSUE THREAD

**Issue by jinfagang** [hongsukchoi/3DCrowdNet_RELEASE#6]
does there any instructions?

**Comment by hongsukchoi** [comment]
SMPL and SMPLX authors shall know better...
But I did find this [project](https://github.com/Dene33/video_to_bvh) and I think you can dig in their codes to change smpl to bvh.

**Comment by NewCoderQ** [comment]
@jinfagang [this](https://github.com/zju3dv/EasyMocap/blob/1c3e5f960beb80b9fd4778248c71658a5d5ec3b3/doc/02_output.md#export-to-bvh-format) may help you

**Comment by jinfagang** [comment]
oh, thank u for the info!
