### ISSUE TITLE
Evaluate CMU-Panoptic Code

### ISSUE THREAD

**Issue by YangChangHee** [hongsukchoi/3DCrowdNet_RELEASE#9]
Thank you for your work!

Can you please provide the code and json file(2D Pose Result) to evalution on the CMU-Panoptic dataset?

=================================================================================
안녕하세요! Github에 논문 코드를 올려주셔서 감사합니다!

Code를 확인해본 결과 CMU-Panoptic 결과를 내면서 사용한 python file과 2D Pose estimation json 파일이 없는 것 같아서 요청드리고자 이슈에 올렸습니다!

감사합니다

**Comment by hongsukchoi** [comment]
Experiments on CMU-Panoptic is done by other author long time ago. You can refer to the code of Jiang, W.; Kolotouros, N.; Pavlakos, G.; Zhou, X.; and Dani- ilidis, K. 2020. Coherent reconstruction of multiple humans from a single image. In CVPR.
We referred their code for evaluation.

Or I could provide messy and raw codes which might not work readily but worth looking

**Comment by YangChangHee** [comment]
I`d really appreciate it if you could give me the raw code
==============================================
raw codes를 제공해주신다면 정말 감사할 것 같습니다!

**Comment by hongsukchoi** [comment]
메일로 보냈습니다~

**Comment by YangChangHee** [comment]
감사합니다!

**Comment by with-twilight** [comment]
The E-mail was sent to you.
Thank you very much.
